services:
  mysql:
    image: 'mysql:8.0.39'
    volumes:
      - data:/var/lib/mysql
    container_name: bside-rdb
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - '3306:3306'
    networks:
      - bside-network
  redis:
    image: 'redis:7.4-alpine'
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10
    container_name: bside-redis
    ports:
      - '6379:6379'
    networks:
      - bside-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: always
    container_name: backend
    env_file:
      - .env
    ports:
      - '8081:8080'
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - bside-network
  prometheus:
    image: prom/prometheus-linux-arm64
    restart: always
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - bside-network
  grafana:
    image: grafana/grafana
    restart: always
    container_name: grafana
    ports:
      - '3000:3000'

networks:
  bside-network:
    name: bside-network
    driver: bridge

volumes:
  data:
