spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: ${KET_STORE}
    key-store-password: ${KET_STORE_PASSWD}
    key-store-type: ${KET_STORE_TYPE}
    key-alias: ${KET_ALIAS}
