spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  docker:
    compose:
      skip:
        in-tests: false
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    bsise.server: debug
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
