spring:
  config:
    activate:
      on-profile: secret_dev
clova:
  api:
    key: ${CLOVASTUDIO_API_KEY}
  apigw:
    key: ${CLOVASTUDIO_APIGW_API_KEY}
  request:
    id: ${CLOVASTUDIO_REQUEST_ID}
  msg:
    separator: "custom-sep"
security:
  jwt:
    token:
      access-key: ${JWT_ACCESS_SECRET}
      refresh-key: ${JWT_REFRESH_SECRET}
  base-url: "http://localhost:3000"
  kakao-admin-key: ${DEV_KAKAO_APP_ADMIN_KEY}
redis:
  expire: ${REDIS_EXPIRE}
  limit: ${REDIS_LIMIT}
