spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
server:
  error:
    whitelabel:
      enabled: false
    include-message: always
  servlet:
    session:
      tracking-modes: cookie
  max-http-request-header-size: 65536
  tomcat:
    mbeanregistry:
      enabled: true
management:
  server:
    port: 9292
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
