## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml
#

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/logs/*.log
    scan_frequency: 10s

output.logstash:
  hosts: ["logstash:5044"]
