global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # prometheus web uri

  - job_name: "spring-actuator"
    metrics_path: '${METRICS_PATH}'
    scrape_interval: 1m
    static_configs:
      - targets: ['${HOST}:${PORT}'] # linux os: {container name}
