spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
server:
  error:
    whitelabel:
      enabled: false
    include-message: always
  servlet:
    session:
      tracking-modes: cookie
