spring:
  application:
    name: admin-server
  profiles:
    group:
      dev: dev, common
      prod: prod, common
  security:
    user:
      name: ${ADMIN_NAME}
      password: ${ADMIN_PASSWD}
server:
  port: ${SERVER_PORT}
