apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana/
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pvc
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: grafana-pv
#  labels:
#    app: grafana-pv
#spec:
#  storageClassName: standard
#  capacity:
#    storage: 2Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: /data/grafana-data
#    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  volumeName: grafana-pv
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi