apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: [ "localhost:9090" ]

      - job_name: "spring-actuator"
        metrics_path: "/actuator/prometheus"
        scrape_interval: 1m
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [ __meta_kubernetes_service_name ]
            action: keep
            regex: api-svc
          - source_labels: [ __meta_kubernetes_service_port_name ]
            action: keep
            regex: actuator  # 9292 포트가 "actuator"라는 이름인지 확인
