apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: [ "localhost:9090" ]

      - job_name: "spring-actuator"
        metrics_path: "/actuator/prometheus"
        scrape_interval: 1m
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [ __meta_kubernetes_service_name ]
            action: keep
            regex: api-svc
          - source_labels: [ __meta_kubernetes_pod_ip ]
            target_label: instance
